[package]
name = "rush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = "1.2.1"
regex = "1.5.5"
lazy_static = "1.4.0"
substring = "1.4.5"
home = "0.5.3"
crossterm = "0.23.2"